Allow x-mode interaction to return only 1 item.
itekako/Chart.js pull request #1
Opened 2017-11-17 13:07 UTC by psaulic

This additional option allows for a simpler implementation of a vertical cursor, returning only 1 item per dataset even for densely populated graphs. Without this option, densely packed graphs return multiple points, cluttering the tooltip and making it unclear which value is being displayed.

2017-11-17 14:46 UTC, minjaitk commented on package.json
> +    "gulp-uglifyes": "0.1.2",
not sure how I feel about adding a new package for syntax purposes and 8 new lines of code

2017-11-17 14:52 UTC, minjaitk requested changes
do this without package changes

2017-11-17 14:52 UTC, minjaitk commented on gulpfile.js
> +var uglify = require('gulp-uglifyes');
I don't like the idea of replacing an existing package just to you can use a certain syntax.
you cannot be sure whether you broke something else with this change.

2017-11-20 11:05 UTC, psaulic commented
@minjaitk Please review the latest changes.

2017-11-20 11:14 UTC, minjaitk approved these changes

2017-11-20 17:00 UTC, merged